// Static catalog of 18 CoachTip entries — Phase 4.40
// See sdd/token-optimizer-v0.1/coach-layer-addendum CO-1

import type { CoachTip } from '../lib/types.js'

export const KNOWLEDGE_BASE: readonly CoachTip[] = [
  {
    id: 'use-opusplan',
    title: 'Usa /opusplan para planificar con Opus y ejecutar con Sonnet',
    description:
      'opusplan usa Opus durante plan mode para razonamiento complejo y vuelve a Sonnet para implementacion. Solo pagas Opus en la fase de planning.',
    savings_estimate: '60-80% de reduccion de coste en sesiones con planning intensivo',
    savings_source: 'community-measured',
    how_to_invoke: '/model opusplan',
    when_applicable: 'Sesiones con razonamiento largo antes de codigo',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: 'detect-long-reasoning-no-code',
  },
  {
    id: 'use-plan-mode',
    title: 'Activa plan mode para exploracion sin escribir codigo',
    description:
      'EnterPlanMode permite razonar y explorar sin hacer ediciones, reduciendo iteraciones costosas.',
    savings_estimate: 'Variable segun tarea',
    savings_source: 'internal',
    how_to_invoke: 'EnterPlanMode tool',
    when_applicable: 'Tareas no triviales antes de escribir codigo',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: 'detect-long-reasoning-no-code',
  },
  {
    id: 'use-fast-mode',
    title: 'Activa /fast para respuestas mas directas',
    description: 'Modo rapido mantiene el modelo pero reduce el detalle de las respuestas.',
    savings_estimate: 'Reduce tiempo principalmente',
    savings_source: 'internal',
    how_to_invoke: '/fast',
    when_applicable: 'Cuando quieres respuestas mas concisas',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: null,
  },
  {
    id: 'default-to-sonnet',
    title: 'Arranca cada sesion con Sonnet y sube a Opus solo cuando haga falta',
    description:
      'Sonnet resuelve ~80% de tareas de coding bien. El switching tactico a Opus solo en razonamiento complejo ahorra el grueso del coste.',
    savings_estimate: '60-80% reduccion de coste total',
    savings_source: 'community-measured',
    how_to_invoke: '/model sonnet (inicio) → /model opus (cuando sea necesario)',
    when_applicable: 'Siempre como default',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: 'detect-opus-for-simple-task',
  },
  {
    id: 'use-haiku-for-simple',
    title: 'Usa Haiku para formato, Q&A simple y tareas de alto volumen',
    description:
      'Haiku es mucho mas barato y rapido. Para formateo, preguntas puntuales o tareas repetitivas es el modelo adecuado.',
    savings_estimate: '~90% reduccion vs Opus en tareas simples',
    savings_source: 'anthropic-docs',
    how_to_invoke: '/model haiku',
    when_applicable: 'Formateo, Q&A simple, alto volumen',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: 'detect-opus-for-simple-task',
  },
  {
    id: 'use-compact-long-session',
    title: 'Corre /compact cuando el contexto supere el 75%',
    description:
      '/compact genera un resumen del contexto actual liberando ~60-80% de la ventana sin perder continuidad.',
    savings_estimate: '60-80% de contexto liberado',
    savings_source: 'community-measured',
    how_to_invoke: '/compact',
    when_applicable: 'Contexto > 75% de la ventana',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: 'detect-context-threshold',
  },
  {
    id: 'use-clear-rename-resume',
    title: 'Usa /rename → /clear → /resume para pivotes de tema',
    description:
      'Al cambiar a un tema no relacionado, renombra la sesion, haz /clear para empezar limpio, y resume cuando vuelvas.',
    savings_estimate: 'Variable segun contexto descartado',
    savings_source: 'internal',
    how_to_invoke: '/rename <nombre> → /clear → (trabajar) → /resume <nombre>',
    when_applicable: 'Pivote total a tema no relacionado',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: 'detect-clear-opportunity',
  },
  {
    id: 'use-sessionstart-compact-hook',
    title: 'Activa el hook SessionStart:compact de token-optimizer',
    description:
      'Cuando Claude Code compacta el contexto, token-optimizer inyecta un resumen con archivos, comandos y presupuesto.',
    savings_estimate: 'Evita re-lectura tras compactacion',
    savings_source: 'internal',
    how_to_invoke: 'token-optimizer-mcp install (ya lo configura)',
    when_applicable: 'Siempre como parte del install',
    source_type: 'mcp',
    verified_at: '2026-04-11',
    detector_id: null,
  },
  {
    id: 'use-memory-save',
    title: 'Guarda decisiones con mem_save antes de compactar',
    description:
      'Persistir decisiones arquitectonicas en engram evita tener que re-derivarlas cuando el contexto se compacta.',
    savings_estimate: 'Variable',
    savings_source: 'internal',
    how_to_invoke: 'mem_save (via engram MCP)',
    when_applicable: 'Antes de /compact o cambiar de sesion',
    source_type: 'mcp',
    verified_at: '2026-04-11',
    detector_id: null,
  },
  {
    id: 'use-agent-explore',
    title: 'Delega busquedas amplias al subagente Explore',
    description:
      'El subagente Explore tiene su propio contexto y no consume el de la sesion principal. Ideal para buscar en muchos archivos.',
    savings_estimate: 'Aisla contexto al subagente',
    savings_source: 'internal',
    how_to_invoke: 'Agent tool con subagent_type="Explore"',
    when_applicable: '3+ busquedas Grep/Glob similares',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: 'detect-repeated-searches',
  },
  {
    id: 'use-todowrite-long-task',
    title: 'Usa TodoWrite para tareas multi-paso',
    description:
      'TodoWrite mantiene el estado de la tarea sin re-leer archivos, reduciendo redundancia.',
    savings_estimate: 'Evita re-lectura de estado',
    savings_source: 'internal',
    how_to_invoke: 'TodoWrite',
    when_applicable: '3+ pasos independientes',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: null,
  },
  {
    id: 'use-skill-trigger',
    title: 'Invoca skills en lugar de re-derivar instrucciones',
    description:
      'Los skills cargan instrucciones especializadas solo cuando se invocan. Mejor que un CLAUDE.md monolitico.',
    savings_estimate: '~15k tokens/sesion con progressive disclosure',
    savings_source: 'community-measured',
    how_to_invoke: 'Skill tool con nombre del skill',
    when_applicable: 'Tareas que matchean un skill disponible',
    source_type: 'skill',
    verified_at: '2026-04-11',
    detector_id: 'detect-skill-trigger-ignored',
  },
  {
    id: 'install-serena',
    title: 'Instala serena-mcp para lecturas simbolicas',
    description:
      'serena usa LSP para leer solo los simbolos que necesitas en lugar del archivo completo. Nota: incluye execute_shell_command.',
    savings_estimate: '20-30% en lecturas de archivos grandes',
    savings_source: 'community-measured',
    how_to_invoke: 'uvx --from git+https://github.com/oraios/serena serena start-mcp-server',
    when_applicable: 'Proyectos con archivos >50k tokens',
    source_type: 'mcp',
    verified_at: '2026-04-11',
    detector_id: 'detect-huge-file-reads',
  },
  {
    id: 'prefer-serena-reads',
    title: 'Usa Serena en vez de Read para archivos de codigo',
    description:
      'Serena lee simbolos (funciones, clases) sin cargar el archivo completo. Usa get_symbols_overview para explorar y find_symbol con include_body para leer solo lo que necesitas. Ahorro tipico: 60-90% vs Read.',
    savings_estimate: '60-90% en lecturas de codigo',
    savings_source: 'internal',
    how_to_invoke: 'get_symbols_overview(path) → find_symbol(name, include_body=true)',
    when_applicable: 'Archivos .ts/.js/.py/.java >50 lineas donde solo necesitas 1-2 funciones',
    source_type: 'mcp',
    verified_at: '2026-04-12',
    detector_id: 'detect-read-over-serena',
  },
  {
    id: 'install-rtk',
    title: 'Instala RTK para filtrar salida ruidosa de Bash',
    description:
      'RTK filtra output de builds/tests antes de llegar a Claude Code. Publica releases firmadas con GPG.',
    savings_estimate: '15-25% en ciclos build/test',
    savings_source: 'community-measured',
    how_to_invoke: 'brew install standard-input/tap/rtk (macOS) o binario firmado en github.com/standard-input/rtk',
    when_applicable: 'Proyectos con builds/tests ruidosos',
    source_type: 'mcp',
    verified_at: '2026-04-11',
    detector_id: 'detect-many-bash-commands',
  },
  {
    id: 'use-mcp-prune',
    title: 'Aplica un allowlist de MCPs por proyecto',
    description:
      'Reduce el coste del tool-schema excluyendo MCPs que no usas en este proyecto. ~5-12% adicional sobre Tool Search.',
    savings_estimate: '5-12% por turno sobre Tool Search nativo',
    savings_source: 'internal',
    how_to_invoke: 'mcp_prune_suggest → mcp_prune_apply',
    when_applicable: 'MCPs registrados pero no usados en el proyecto',
    source_type: 'mcp',
    verified_at: '2026-04-11',
    detector_id: 'detect-unused-mcp-servers',
  },
  {
    id: 'migrate-claudemd-to-skills',
    title: 'Migra CLAUDE.md grande a skills con progressive disclosure',
    description:
      'Un CLAUDE.md monolitico se carga en cada sesion. Los skills solo cargan cuando se invocan. ~15k tokens recuperados.',
    savings_estimate: '~15k tokens/sesion (82% mejor que CLAUDE.md monolitico)',
    savings_source: 'community-measured',
    how_to_invoke: 'Crear skills en .claude/skills/ con triggers especificos',
    when_applicable: 'CLAUDE.md > 10k tokens con uso parcial',
    source_type: 'skill',
    verified_at: '2026-04-11',
    detector_id: 'detect-claudemd-bloat',
  },
  {
    id: 'use-settings-local',
    title: 'Configuracion personal en settings.local.json',
    description:
      'Evita contaminar settings.json del equipo. settings.local.json es personal y gitignored por defecto.',
    savings_estimate: 'Higiene, no tokens',
    savings_source: 'internal',
    how_to_invoke: 'Editar .claude/settings.local.json',
    when_applicable: 'Configuracion personal no compartible',
    source_type: 'settings',
    verified_at: '2026-04-11',
    detector_id: null,
  },
  {
    id: 'use-serena-overview-first',
    title: 'Usa get_symbols_overview antes de find_symbol',
    description:
      'Llamar get_symbols_overview una vez da el mapa del archivo. Las llamadas sucesivas find_symbol sin overview previo leen el mismo archivo repetidamente.',
    savings_estimate: '30-50% menos llamadas Serena por sesion',
    savings_source: 'internal',
    how_to_invoke: 'mcp__serena__get_symbols_overview con relative_path antes de find_symbol',
    when_applicable: 'Al explorar un archivo por primera vez en la sesion',
    source_type: 'mcp',
    verified_at: '2026-04-15',
    detector_id: 'detect-serena-read-cascade',
  },
  {
    id: 'use-prompt-caching',
    title: 'Estructura prompts para maximizar cache hits',
    description:
      'Los tokens leidos del cache cuestan 10x menos. Mantener el prefijo estable (system, CLAUDE.md) aprovecha el cache.',
    savings_estimate: '10x mas barato en reads cacheados',
    savings_source: 'anthropic-docs',
    how_to_invoke: 'Mantener prefijo estable entre turns',
    when_applicable: 'Siempre',
    source_type: 'built-in',
    verified_at: '2026-04-11',
    detector_id: null,
  },
]
